import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  nb: { translation: {
    nav: { master: 'Master', projects: 'Prosjekter', system: 'System' },
    common: { loading: 'Laster…', refresh: 'Oppdater', cancel: 'Avbryt', save: 'Lagre', close: 'Lukk', ready: 'Klar', configure: 'Konfigurer', add: 'Legg til', remove: 'Fjern', edit: 'Rediger' },
    setup: {
      eyebrow: 'FØRSTEGANGSOPPSETT', title: 'Gjør AI Dashboard klart',
      intro: 'Velg prosjektmappe og standardmodeller én gang. Du kan endre alt senere.',
      language: 'Språk', root: 'Prosjektmappe', rootHint: 'For eksempel C:\\Projects eller /home/marius/Projects',
      coding: 'Standard kodemodell', master: 'Master-modell', finish: 'Fullfør oppsett',
      opencodeOk: 'OpenCode er funnet', opencodeMissing: 'OpenCode er ikke tilgjengelig ennå. Prosjekter og oppsett kan fortsatt brukes; Master krever en direkte modellprovider.'
    },
    master: {
      eyebrow: 'PERSONLIG ASSISTENT', title: 'Master', newChat: 'Ny samtale',
      emptyTitle: 'Hva vil du gjøre?', emptyCopy: 'Spør om hva som helst. Når du vil starte arbeid kan Master bruke Dashboard-verktøyene.',
      placeholder: 'Skriv til Master…', send: 'Send', global: 'Generell samtale', project: 'Prosjektkontekst',
      noModel: 'Ingen Master-modell valgt', you: 'Du', messageCount: '{{count}} melding', messageCount_other: '{{count}} meldinger'
    },
    projects: {
      eyebrow: 'ARBEIDSOMRÅDER', title: 'Prosjekter', discover: 'Importer prosjekt', create: 'Nytt lokalt prosjekt',
      empty: 'Ingen prosjekter ennå.', emptyCopy: 'Importer et eksisterende Git-repo eller opprett et nytt lokalt prosjekt.',
      usable: 'Klar til bruk', managed: 'Administrert', localProject: 'Lokalt prosjekt', automation: 'Autonomi må konfigureres', open: 'Åpne', tasks: 'oppgaver',
      createTitle: 'Nytt lokalt prosjekt', name: 'Navn', folder: 'Mappenavn', description: 'Beskrivelse', root: 'Plassering', createAction: 'Opprett prosjekt',
      discoverTitle: 'Importer eksisterende prosjekt', scan: 'Skann prosjektmapper', import: 'Importer', cloneImport: 'Klon og importer', remoteRepo: 'GitHub-repo', noRepos: 'Ingen nye Git-repoer funnet.'
    },
    project: {
      back: 'Tilbake til prosjekter', overview: 'Oversikt', tasks: 'Oppgaver', readiness: 'Autonomi',
      navigation: 'Prosjektnavigasjon', tabs: { overview: 'Oversikt', tasks: 'Oppgaver', agents: 'Agenter', github: 'GitHub', evidence: 'Evidens', research: 'Research', settings: 'Innstillinger' },
      normalUse: 'Normal bruk', strictReadiness: 'Autonom kjøring', createTask: 'Ny oppgave',
      title: 'Tittel', description: 'Beskrivelse', criteria: 'Akseptansekriterier', criteriaHint: 'Påkrevd. Én verdi per linje eller kommaseparert.', create: 'Opprett oppgave',
      eyebrow: 'PROSJEKT', notFound: 'Prosjektet finnes ikke', blockerCount: '{{count}} blokkering', blockerCount_other: '{{count}} blokkeringer', readinessHint: 'Kjør kontroll når du skal delegere kode.', checkReadiness: 'Sjekk autonomi', noTasks: 'Ingen oppgaver ennå.', noTasksHint: 'Opprett en konkret oppgave med akseptansekriterier når du vil starte arbeid.',
      listHint: 'Én verdi per linje eller kommaseparert.', workScopes: 'Arbeidsområder', agent: 'Agent', unassigned: 'Ikke tildelt', activeRuns: 'Aktive kjøringer', openTasks: 'Åpne oppgaver', next: 'Neste viktige steg', noOpenWork: 'Ingen åpent arbeid', noOpenWorkHint: 'Prosjektet er klart for neste oppgave.',
      usabilityReady: 'Prosjektet er klart til bruk. Autonom kjøring har egne readiness-gater.', usabilityNoRepo: 'Prosjektet er klart for chat, planlegging og oppgaver; koble til et repository før koding.', usabilityRepair: 'Prosjektkonfigurasjonen må repareres før normal bruk.',
      codingLane: 'KODEFLYT', codingFlow: 'Oppgave → worker → evidens → PR / CI → supervisor → merge', researchLane: 'RESEARCH', researchFlow: 'Prosjekt → Research Run → provider / modell → lagret rapport', researchReadOnly: 'Separat read-only flyt uten worktree eller merge-loop.'
    },
    task: { delegate: 'Deleger', respond: 'Svar', respondTitle: 'Svar på blokkering', response: 'Beslutning eller kontekst', resume: 'Gjør oppgaven klar for ny kjøring etter at svaret er lagret', publish: 'Opprett PR', refreshCi: 'Oppdater CI', review: 'Start supervisor', merge: 'Merge godkjent arbeid' },
    agent: { title: 'Spesialister', create: 'Ny agent', name: 'Navn', role: 'Rolle', model: 'Modell', scopes: 'Arbeidsområder', capabilities: 'Egenskaper', instructions: 'Instruksjoner', inherited: 'arver prosjektmodell', active: 'aktiv kjøring', enable: 'Aktiver', disable: 'Deaktiver', empty: 'Ingen spesialister ennå', emptyHint: 'Lag bare agenter når ansvar og arbeidsområder er tydelig avgrenset.' },
    github: { notConnected: 'GitHub er ikke koblet til prosjektet', notConnectedHint: 'Importer et repository med GitHub-origin eller angi repository i prosjektinnstillingene.', noPublication: 'Ingen publiseringsevidens ennå' },
    evidence: { title: 'Maskinevidens', empty: 'Ingen evidens ennå', emptyHint: 'Evidens dukker opp når en oppgave har en kjøring eller publikasjon.', code: 'Kode', verification: 'Verifikasjon', github: 'GitHub', checkpoint: 'Checkpoint', scope: 'Scope', runStatus: 'Kjøringsstatus', model: 'Modell', error: 'Feil', advanced: 'Avansert rådata' },
    research: { title: 'Prosjektresearch', create: 'Ny research', readOnly: 'Research er en separat read-only flyt. Den oppretter ikke worktree, PR eller merge.', prompt: 'Hva skal undersøkes?', model: 'Direktemodell', empty: 'Ingen researchkjøringer ennå', emptyHint: 'Bruk Research for analyse av prosjektet uten å starte kodearbeid.' },
    settings: { project: 'Prosjektinnstillinger', baseBranch: 'Base branch', verification: 'Verifikasjonskommandoer' },
    states: { backlog: 'Klar for arbeid', planning: 'Planlegges', in_progress: 'Worker arbeider', awaiting_publish: 'Klar for PR', awaiting_ci: 'GitHub-tester kjører', awaiting_review: 'Venter på supervisor', reviewing: 'Supervisor vurderer', ready_to_merge: 'Klar for merge', needs_input: 'Trenger svar fra deg', waiting_dependencies: 'Venter på avhengigheter', repair_required: 'Må repareres', done: 'Ferdig' },
    projectStates: { active: 'Aktivt', needs_sync: 'Må synkroniseres', paused: 'Pauset', blocked: 'Blokkert', archived: 'Arkivert' },
    system: {
      eyebrow: 'KONTROLLPLAN', title: 'System', intro: 'Velg modellendepunkter, rollemodeller og lokale prosjektmapper uten å legge hemmeligheter i Dashboard-state.', language: 'Språk', models: 'Rollemodeller', integrations: 'Integrasjoner',
      opencode: 'OpenCode', opencodeOffline: 'OpenCode frakoblet', github: 'GitHub', persistence: 'Lagring', masterModel: 'Master-modell', masterModelHint: 'Master bruker en direkte OpenAI-kompatibel provider, ikke OpenCode-harnesset.', codingModel: 'Kodermodell', planningModel: 'Plannermodell', supervisorModel: 'Supervisormodell', researchModel: 'Researchmodell', configured: 'konfigurert', optional: 'valgfritt', workspaceRoots: 'Prosjektmapper', workspaceRootsHint: 'Dashboard skanner bare direkte undermapper i disse privilegerte plasseringene.', none: 'ingen',
      providers: 'Modellprovidere og API-er', providersHint: 'Legg til et OpenAI-kompatibelt endepunkt og oppdag modellene det tilbyr.', addProvider: 'Legg til provider', editProvider: 'Rediger provider', discoveredModels: 'modeller', discoverModels: 'Oppdag modeller', noCredential: 'ingen credential kreves', providerSecretHint: 'Selve API-nøkkelen lagres aldri her. Oppgi bare navnet på miljøvariabelen som inneholder nøkkelen, og restart Dashboard etter at miljøvariabelen er satt.', providerId: 'Provider-ID', providerName: 'Visningsnavn', baseUrl: 'Base-URL', apiKeyEnv: 'Miljøvariabel for API-nøkkel', apiKeyEnvHint: 'For eksempel OPENROUTER_API_KEY. La stå tomt for lokale endepunkter uten nøkkel.', modelsHint: 'Standardene arves av nye prosjekter. Hvert prosjekt kan overstyre dem.', available: 'tilgjengelige', saveModels: 'Lagre modellvalg',
      masterIdentity: 'Master-identitet og læring', masterIdentityHint: 'Master bruker en lokal SOUL.md og et redigerbart minne. Dette er kontekst, aldri maskinevidens.', soul: 'SOUL.md', soulHint: 'Personlighet og arbeidsprinsipper. Kontrollplanets sikkerhetsregler kan ikke overstyres her.', memory: 'Hva Master husker', memoryHint: 'Automatisk læring lagrer bare varig kontekst med kilde og confidence. Du kan redigere eller slette alt.', remember: 'Husk dette', forget: 'Glem', memoryEmpty: 'Master har ikke lagret varig minne ennå.', memoryPlaceholder: 'For eksempel: Jeg foretrekker korte statusrapporter med konkrete bevis.', memoryProfile: 'Profil', memoryPreference: 'Preferanse', memoryGoal: 'Mål', memoryConvention: 'Arbeidsmåte', memoryLesson: 'Lært prinsipp'
    }
  } },
  en: { translation: {
    nav: { master: 'Master', projects: 'Projects', system: 'System' },
    common: { loading: 'Loading…', refresh: 'Refresh', cancel: 'Cancel', save: 'Save', close: 'Close', ready: 'Ready', configure: 'Configure', add: 'Add', remove: 'Remove', edit: 'Edit' },
    setup: {
      eyebrow: 'FIRST-RUN SETUP', title: 'Get AI Dashboard ready', intro: 'Choose your project folder and default models once. Everything can be changed later.',
      language: 'Language', root: 'Projects folder', rootHint: 'For example C:\\Projects or /home/me/Projects', coding: 'Default coding model', master: 'Master model', finish: 'Finish setup',
      opencodeOk: 'OpenCode detected', opencodeMissing: 'OpenCode is not available yet. Projects and setup still work; Master requires a direct model provider.'
    },
    master: { eyebrow: 'PERSONAL ASSISTANT', title: 'Master', newChat: 'New conversation', emptyTitle: 'What do you want to do?', emptyCopy: 'Ask anything. When you want work started, Master can use Dashboard tools.', placeholder: 'Message Master…', send: 'Send', global: 'General conversation', project: 'Project context', noModel: 'No Master model selected', you: 'You', messageCount: '{{count}} message', messageCount_other: '{{count}} messages' },
    projects: { eyebrow: 'WORKSPACES', title: 'Projects', discover: 'Import project', create: 'New local project', empty: 'No projects yet.', emptyCopy: 'Import an existing Git repository or create a new local project.', usable: 'Ready to use', managed: 'Managed', localProject: 'Local project', automation: 'Autonomy needs setup', open: 'Open', tasks: 'tasks', createTitle: 'New local project', name: 'Name', folder: 'Folder name', description: 'Description', root: 'Location', createAction: 'Create project', discoverTitle: 'Import existing project', scan: 'Scan project folders', import: 'Import', cloneImport: 'Clone & import', remoteRepo: 'GitHub repository', noRepos: 'No new Git repositories found.' },
    project: { back: 'Back to projects', overview: 'Overview', tasks: 'Tasks', readiness: 'Autonomy', navigation: 'Project navigation', tabs: { overview: 'Overview', tasks: 'Tasks', agents: 'Agents', github: 'GitHub', evidence: 'Evidence', research: 'Research', settings: 'Settings' }, normalUse: 'Normal use', strictReadiness: 'Autonomous execution', createTask: 'New task', title: 'Title', description: 'Description', criteria: 'Acceptance criteria', criteriaHint: 'Required. One value per line or comma-separated.', create: 'Create task', eyebrow: 'PROJECT', notFound: 'Project not found', blockerCount: '{{count}} blocker', blockerCount_other: '{{count}} blockers', readinessHint: 'Run the check when you are ready to delegate coding work.', checkReadiness: 'Check autonomy', noTasks: 'No tasks yet.', noTasksHint: 'Create a concrete task with acceptance criteria when you want to start work.', listHint: 'One value per line or comma-separated.', workScopes: 'Work scopes', agent: 'Agent', unassigned: 'Unassigned', activeRuns: 'Active runs', openTasks: 'Open tasks', next: 'Next important step', noOpenWork: 'No open work', noOpenWorkHint: 'The Project is ready for its next task.', usabilityReady: 'Project is ready to use. Autonomous execution has separate readiness gates.', usabilityNoRepo: 'Project is ready for chat, planning and Tasks; bind a repository before coding.', usabilityRepair: 'Project configuration needs repair before normal use.', codingLane: 'CODING LANE', codingFlow: 'Task → worker → evidence → PR / CI → supervisor → merge', researchLane: 'RESEARCH', researchFlow: 'Project → Research Run → provider / model → persisted report', researchReadOnly: 'Separate read-only lane without worktrees or the merge loop.' },
    task: { delegate: 'Delegate', respond: 'Respond', respondTitle: 'Respond to blocker', response: 'Decision or context', resume: 'Make the Task eligible for another run after saving the response', publish: 'Create PR', refreshCi: 'Refresh CI', review: 'Start supervisor', merge: 'Merge approved work' },
    agent: { title: 'Specialists', create: 'New agent', name: 'Name', role: 'Role', model: 'Model', scopes: 'Work scopes', capabilities: 'Capabilities', instructions: 'Instructions', inherited: 'inherits Project model', active: 'active run', enable: 'Enable', disable: 'Disable', empty: 'No specialists yet', emptyHint: 'Create agents only when responsibility and work scopes are clearly bounded.' },
    github: { notConnected: 'GitHub is not connected to this Project', notConnectedHint: 'Import a repository with a GitHub origin or set the repository in Project Settings.', noPublication: 'No publication evidence yet' },
    evidence: { title: 'Machine evidence', empty: 'No evidence yet', emptyHint: 'Evidence appears after a Task has a Run or publication.', code: 'Code', verification: 'Verification', github: 'GitHub', checkpoint: 'Checkpoint', scope: 'Scope', runStatus: 'Run status', model: 'Model', error: 'Error', advanced: 'Advanced raw data' },
    research: { title: 'Project Research', create: 'New Research', readOnly: 'Research is a separate read-only lane. It does not create a worktree, PR or merge.', prompt: 'What should be investigated?', model: 'Direct model', empty: 'No Research Runs yet', emptyHint: 'Use Research to analyze the Project without starting coding work.' },
    settings: { project: 'Project Settings', baseBranch: 'Base branch', verification: 'Verification commands' },
    states: { backlog: 'Ready for work', planning: 'Planning', in_progress: 'Worker working', awaiting_publish: 'Ready for PR', awaiting_ci: 'GitHub tests running', awaiting_review: 'Waiting for supervisor', reviewing: 'Supervisor reviewing', ready_to_merge: 'Ready to merge', needs_input: 'Needs your input', waiting_dependencies: 'Waiting for dependencies', repair_required: 'Repair required', done: 'Done' },
    projectStates: { active: 'Active', needs_sync: 'Needs sync', paused: 'Paused', blocked: 'Blocked', archived: 'Archived' },
    system: { eyebrow: 'CONTROL PLANE', title: 'System', intro: 'Choose model endpoints, role defaults and local Project roots without storing secrets in Dashboard state.', language: 'Language', models: 'Role models', integrations: 'Integrations', opencode: 'OpenCode', opencodeOffline: 'OpenCode offline', github: 'GitHub', persistence: 'Persistence', masterModel: 'Master model', masterModelHint: 'Master uses a direct OpenAI-compatible provider, not the OpenCode harness.', codingModel: 'Coding model', planningModel: 'Planner model', supervisorModel: 'Supervisor model', researchModel: 'Research model', configured: 'configured', optional: 'optional', workspaceRoots: 'Workspace roots', workspaceRootsHint: 'Dashboard scans only direct children of these privileged locations.', none: 'none', providers: 'Model providers and APIs', providersHint: 'Add an OpenAI-compatible endpoint and discover the models it exposes.', addProvider: 'Add provider', editProvider: 'Edit provider', discoveredModels: 'models', discoverModels: 'Discover models', noCredential: 'no credential required', providerSecretHint: 'The API key itself is never stored here. Enter only the environment-variable name that contains it, then restart Dashboard after setting the variable.', providerId: 'Provider ID', providerName: 'Display name', baseUrl: 'Base URL', apiKeyEnv: 'API-key environment variable', apiKeyEnvHint: 'For example OPENROUTER_API_KEY. Leave blank for local endpoints that need no key.', modelsHint: 'Defaults are inherited by new Projects. Each Project can override them.', available: 'available', saveModels: 'Save model choices', masterIdentity: 'Master identity and learning', masterIdentityHint: 'Master uses a local SOUL.md and editable memory. This is context, never machine evidence.', soul: 'SOUL.md', soulHint: 'Persona and working principles. Control-plane safety rules cannot be overridden here.', memory: 'What Master remembers', memoryHint: 'Automatic learning stores only durable context with source and confidence. Everything can be edited or deleted.', remember: 'Remember this', forget: 'Forget', memoryEmpty: 'Master has no durable memories yet.', memoryPlaceholder: 'For example: I prefer concise status reports with concrete evidence.', memoryProfile: 'Profile', memoryPreference: 'Preference', memoryGoal: 'Goal', memoryConvention: 'Convention', memoryLesson: 'Learned principle' }
  } },
} as const;

void i18n.use(initReactI18next).init({
  resources,
  lng: 'nb',
  fallbackLng: 'nb',
  interpolation: { escapeValue: false },
});

export default i18n;
